package pkgs

import (
	"github.com/gogf/gf/v2/encoding/gjson"
	"github.com/gogf/gf/v2/frame/g"
	"github.com/gogf/gf/v2/util/gconv"
	"goframe-ex/egoja/gojaapi"
)

func init() {

	gojaapi.RegisterImport("gf/g", map[string]any{
		"Var":        g.Var{},
		"Meta":       g.Meta{},
		"Map":        g.Map{},
		"MapAnyAny":  g.MapAnyAny{},
		"MapAnyStr":  g.MapAnyStr{},
		"MapAnyInt":  g.MapAnyInt{},
		"MapStrStr":  g.MapStrStr{},
		"MapStrInt":  g.MapStrInt{},
		"MapIntAny":  g.MapIntAny{},
		"MapIntBool": g.MapIntBool{},
		"MapStrBool": g.MapStrBool{},
		"MapAnyBool": g.MapAnyBool{},
		"MapIntInt":  g.MapIntInt{},
		"MapIntStr":  g.MapIntStr{},

		"ArrayInt":    g.ArrayInt{},
		"ArrayStr":    g.ArrayStr{},
		"ArrayAny":    g.ArrayAny{},
		"Array":       g.Array{},
		"SliceInt":    g.SliceInt{},
		"SliceStr":    g.SliceStr{},
		"SliceAny":    g.SliceAny{},
		"Slice":       g.Slice{},
		"ListIntBool": g.ListIntBool{},
		"ListStrBool": g.ListStrBool{},
		"ListAnyBool": g.ListAnyBool{},
		"ListIntInt":  g.ListIntInt{},
		"ListIntStr":  g.ListIntStr{},
		"ListIntAny":  g.ListIntAny{},
		"ListStrInt":  g.ListStrInt{},
		"ListStrStr":  g.ListStrStr{},
		"ListStrAny":  g.ListStrAny{},
		"ListAnyInt":  g.ListAnyInt{},
		"ListAnyStr":  g.ListAnyStr{},
		"ListAnyAny":  g.ListAnyAny{},
		"List":        g.List{},

		// func
		"Go":             g.Go,
		"NewVar":         g.NewVar,
		"Wait":           g.Wait,
		"Listen":         g.Listen,
		"Dump":           g.Dump,
		"DumpTo":         g.DumpTo,
		"DumpWithType":   g.DumpWithType,
		"DumpWithOption": g.DumpWithOption,
		"DumpJson":       g.DumpJson,
		"Try":            g.Try,
		"TryCatch":       g.TryCatch,
		"Throw":          g.Throw,
		"IsNil":          g.IsNil,
		"RequestFromCtx": g.RequestFromCtx,
		"Client":         g.Client,
		"Server":         g.Server,
		"TCPServer":      g.TCPServer,
		"UDPServer":      g.UDPServer,
		"View":           g.View,
		"Config":         g.Config,
		"Cfg":            g.Cfg,
		"Resource":       g.Resource,
		"I18n":           g.I18n,
		"Log":            g.Log,
		"DB":             g.DB,
		"Model":          g.Model,
		"ModelRaw":       g.ModelRaw,
		"Redis":          g.Redis,
		"Validator":      g.Validator,
		"SetDebug":       g.SetDebug,
	})

	gojaapi.RegisterImport("gf/gjson", map[string]any{
		"New":                   gjson.New,
		"NewWithTag":            gjson.NewWithTag,
		"NewWithOptions":        gjson.NewWithOptions,
		"Load":                  gjson.LoadPath,
		"LoadWithOptions":       gjson.LoadWithOptions,
		"LoadJson":              gjson.LoadJson,
		"LoadXml":               gjson.LoadXml,
		"LoadIni":               gjson.LoadIni,
		"LoadYaml":              gjson.LoadYaml,
		"LoadToml":              gjson.LoadToml,
		"LoadProperties":        gjson.LoadProperties,
		"LoadContent":           gjson.LoadContent,
		"LoadContentType":       gjson.LoadContentType,
		"IsValidDataType":       gjson.IsValidDataType,
		"Valid":                 gjson.Valid,
		"Marshal":               gjson.Marshal,
		"MarshalIndent":         gjson.MarshalIndent,
		"Unmarshal":             gjson.Unmarshal,
		"Encode":                gjson.Encode,
		"MustEncode":            gjson.MustEncode,
		"EncodeString":          gjson.EncodeString,
		"MustEncodeString":      gjson.MustEncodeString,
		"Decode":                gjson.Decode,
		"DecodeTo":              gjson.DecodeTo,
		"DecodeToJson":          gjson.DecodeToJson,
		"ContentTypeJson":       gjson.ContentTypeJSON,
		"ContentTypeJs":         gjson.ContentTypeJs,
		"ContentTypeXml":        gjson.ContentTypeXML,
		"ContentTypeIni":        gjson.ContentTypeIni,
		"ContentTypeYaml":       gjson.ContentTypeYaml,
		"ContentTypeYml":        gjson.ContentTypeYml,
		"ContentTypeToml":       gjson.ContentTypeToml,
		"ContentTypeProperties": gjson.ContentTypeProperties,
	})

	gojaapi.RegisterImport("gf/gconv", map[string]any{
		"String":           gconv.String,
		"Strings":          gconv.Strings,
		"Interfaces":       gconv.Interfaces,
		"Byte":             gconv.Byte,
		"Bytes":            gconv.Bytes,
		"Rune":             gconv.Rune,
		"Runes":            gconv.Runes,
		"Bool":             gconv.Bool,
		"Float32":          gconv.Float32,
		"Float64":          gconv.Float64,
		"Int":              gconv.Int,
		"Int8":             gconv.Int8,
		"Int16":            gconv.Int16,
		"Int32":            gconv.Int32,
		"Int64":            gconv.Int64,
		"Uint":             gconv.Uint,
		"Uint8":            gconv.Uint8,
		"Uint16":           gconv.Uint16,
		"Uint32":           gconv.Uint32,
		"Uint64":           gconv.Uint64,
		"MapOption":        gconv.MapOption{},
		"Map":              gconv.Map,
		"Maps":             gconv.Maps,
		"MapsDeep":         gconv.MapsDeep,
		"MapDeep":          gconv.MapDeep,
		"MapStrStr":        gconv.MapStrStr,
		"MapStrStrDeep":    gconv.MapStrStrDeep,
		"PtrAny":           gconv.PtrAny,
		"Scan":             gconv.Scan,
		"Time":             gconv.Time,
		"Duration":         gconv.Duration,
		"GTime":            gconv.GTime,
		"Convert":          gconv.Convert,
		"ConvertWithRefer": gconv.ConvertWithRefer,
	})
}
